version: "3.5"

services:
  web:
    image: webdevops/php-nginx:7.2
    working_dir: /app
    ports:
      - 81:80
    depends_on:
      - database
    volumes:
      - .:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      PHP_DATE_TIMEZONE: "Europe/Paris"
      PHP_DISPLAY_ERRORS: 1

  database:
    image: mysql:8.0
    command: mysqld --sql_mode=""
    volumes:
      - ./docker/mysqlconf:/etc/mysql/conf.d
      - ./docker/mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: symfonyprojet
      MYSQL_ROOT_PASSWORD: root
      
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    restart:  always
    ports:
      - "8025:8025"
      - "1025:1025"
